name: 'backend-radiodiagnosis-v1'

services:
  backend:
    container_name: backend-express
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        - NODE_ENV=production
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
#    volumes:
#      - .:/app